### ISSUE TITLE
Un - decode - able

### ISSUE THREAD

**Issue by 0xMirasio** [oliver408i/PYO-Python-obfuscator#1]
```compile() - The fourth layer is basically un-decode-able. The code is made into binary and marshalled (so that it can be represented in text). There is no way to decode this as it is binary. The best applications packaged to this (think Chrome: did anyone get the source code of chrome? -NOT Chromeium)``` 

well...
no? 

marshall bytes python objects is just a pyc file in bytes format. So you just can use a pyc to py decompiler and get the obfusacted code.
then you just break to the last line executing the final decoded payload...

well try tho ^^

**Comment by oliver408i** [comment]
yea ik. i made this before i learned how python works
